### ISSUE TITLE
Keyboard shortcuts al in HTML

### ISSUE THREAD

**Issue by KrijnHoetmer** [linda2912/linda2912.github.io#11]
In je HTML source heb je de toetsenbord-hints al staan; wat nou als ik op een apparaat zit zonder toetsenbord, zoals een iPhone? Probeer keyboard interactie als enhancement te zien. Zijn die karakters toe te voegen met JS?

**Comment by linda2912** [comment]
Ik heb de karakters nu met js toegevoegd maar ik kan niet controleren of de gebruiker een toetsenbord heeft.. Kan ik de issue sluiten?

**Comment by KrijnHoetmer** [comment]
Je weet in ieder geval zeker dat zonder JavaScript het toetsenbord niet werkt (hoewel, heb je naar het `accesskey` attribuut gekeken?), dus ik zou deze letters in ieder geval met JS toevoegen aan de buttons.

**Comment by KrijnHoetmer** [comment]
Whoeps, sorry!

**Comment by KrijnHoetmer** [comment]
Ja, beter zo, nice! :)
