### ISSUE TITLE
Twee varianten van hetzelfde gemaakt in HTML

### ISSUE THREAD

**Issue by KrijnHoetmer** [linda2912/linda2912.github.io#12]
Je hebt in HTML nu eigenlijk twee applicaties gemaakt; eentje voor 'zielige' browsers en eentje voor 'fancy' browsers. Op zich niet verkeerd natuurlijk, en voor deze beatbox kan dat nog wel, maar hoe zou je dit doen bij een grotere applicatie? Bouw je dan ook twee (of meer) interfaces op? Probeer je HTML zo op te zetten dat je het kunt verrijken, in plaats van dat je moet switchen tussen twee varianten.

**Comment by linda2912** [comment]
Ik heb nu de met javascript de audio elementen vervangen door buttons zodat ik geen dubbele scripts meer in mijn html heb.

var button = document.createElement('button'); //create button element
var dataKey = div[i].querySelector('audio').getAttribute('data-key'); //pick all data-key's  
var keyString = String.fromCharCode(dataKey); //converts unicode values into characters.
button.innerHTML = div[i].querySelector('p').innerHTML + ' (' + keyString + ')'; //add html into the button
div[i].appendChild(button); //append an button element into all divs
button.addEventListener(handler, play, false); //onclick execute the play function
audios[i].removeAttribute('controls'); //remove all the controls from the audio elements  
keys[dataKey] = button;
