### ISSUE TITLE
Feature detection in JS ontbreekt

### ISSUE THREAD

**Issue by KrijnHoetmer** [linda2912/linda2912.github.io#14]
Je doet nu de aanname dat als JS aan staat ook meteen de 'andere' interface getoond moet worden, maar wat als een browser per ongeluk wel `classList` ondersteunt, maar `new Audio()` niet? Of wat als audio wel ondersteund wordt, maar `classList` niet (IE9)?

**Comment by linda2912** [comment]
Ik check nu of de browser classlist en audio ondersteund, dan wordt pas de code uitgevoerd.

if (classListAvailable && mediaSupport) { //check if classlist and audio is supported
