### ISSUE TITLE
Hoeveel code moet je aanpassen om een nieuwe knop toe te voegen?

### ISSUE THREAD

**Issue by KrijnHoetmer** [linda2912/linda2912.github.io#15]
Een goede test voor PE: stel je voegt nu in je HTML een nieuwe knop met een nieuw geluid toe, hoeveel code moet je dan aanpassen? Op dit moment moet je in JavaScript ook een heleboel doen. Probeer je JS zo op te zetten dat je je HTML makkelijker kunt aanpassen/uitbreiden (wat je redelijk automatisch in CSS ook al doet).

**Comment by linda2912** [comment]
Ik heb de audio src direct in de html toegevoegd en de javascript zo geschreven dat er niets aangepast hoeft te worden als er een audio element wordt toegevoegd.
