### ISSUE TITLE
IOT: veel code voor thingspeak kan weg

### ISSUE THREAD

**Issue by LeanderVanBaekel** [linda2912/linda2912.github.io#16]
Hij checkt nu wat voor bord je gebruikt, dit is niet perse nodig, kijk bijvoorbeeld bij Raymond: [https://github.com/RaymondKorrel/iot/blob/master/thingspeak/thingspeak.ino](https://github.com/RaymondKorrel/iot/blob/master/thingspeak/thingspeak.ino)

**Comment by linda2912** [comment]
Thanks!
