### ISSUE TITLE
Keys in IoT Cloudservices

### ISSUE THREAD

**Issue by Wasknijper** [linda2912/linda2912.github.io#17]
Vergeet vooral niet om je keys ook weg te halen:
https://github.com/linda2912/linda2912.github.io/blob/master/internetOfThings/week1/avv1ThingSpeak/avv1ThingSpeak.ino#L18
https://github.com/linda2912/linda2912.github.io/blob/master/internetOfThings/week1/avv1EasyloT/avv1EasyloT.ino#L51
https://github.com/linda2912/linda2912.github.io/blob/master/internetOfThings/week1/avv1EasyloT/avv1EasyloT.ino#L52

Anders kunnen andere mensen er ook gebruik van maken.

**Comment by linda2912** [comment]
Goed punt.
